# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NDMVRP
                                 A QGIS plugin
 this plugin creates VRP strategies for NDM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-14
        copyright            : (C) 2023 by AEM
        email                : sid.mpadhyay@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NDMVRP class from file NDMVRP.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .NDMVRP import NDMVRP
    return NDMVRP(iface)
