# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NDMVRP
                                 A QGIS plugin
 this plugin creates VRP strategies for NDM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-14
        copyright            : (C) 2023 by AEM
        email                : sid.mpadhyay@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NDMVRP class from file NDMVRP.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    _ensure_dependencies()
    from .NDMVRP import NDMVRP
    return NDMVRP(iface)


def _ensure_dependencies():
    """Check for required packages and install any that are missing or broken.

    Runs automatically on every plugin load. Packages with known DLL issues
    in QGIS environments (Pillow, lxml) are always force-reinstalled to
    replace any corrupted C extensions left by a previous bad install.

    Packages managed:
        - openpyxl : pandas needs this to write .xlsx files
        - lxml     : fontTools/matplotlib PDF backend needs this
        - Pillow   : matplotlib needs this for image rendering
    """
    import os
    import sys
    import subprocess
    from qgis.PyQt.QtWidgets import QMessageBox

    # In QGIS, sys.executable points to qgis-bin.exe, not python.exe.
    # sys.exec_prefix correctly locates the QGIS Python installation.
    python_exe = os.path.join(sys.exec_prefix, 'python.exe')
    if not os.path.exists(python_exe):
        python_exe = sys.executable  # fallback for non-Windows

    # Packages that only need a simple import check.
    simple_packages = {
        'openpyxl': 'openpyxl',
    }

    # Packages with known DLL issues in QGIS environments.
    # A surface-level import succeeds even when the C extension is broken,
    # so we do a deeper runtime check and always force-reinstall if broken.
    dll_sensitive_packages = {
        'Pillow': 'from PIL import Image; Image.new("RGB", (1,1))',
        'lxml':   'from lxml import etree',
    }

    to_install_normal = []
    to_reinstall_forced = []

    for pip_name, import_name in simple_packages.items():
        if not _can_import(import_name):
            to_install_normal.append(pip_name)

    for pip_name, test_expr in dll_sensitive_packages.items():
        if not _can_import_deep(test_expr):
            to_reinstall_forced.append(pip_name)

    all_to_fix = to_install_normal + to_reinstall_forced
    if not all_to_fix:
        return  # everything is healthy — nothing to do

    QMessageBox.information(
        None,
        "NDMVRP — Installing Dependencies",
        f"The following packages are missing or have broken DLLs and will "
        f"be (re)installed now:\n\n"
        f"  {',  '.join(all_to_fix)}\n\n"
        f"Please wait — this only happens once on a new machine."
    )

    failed = []

    for package in to_install_normal:
        result = subprocess.run(
            [python_exe, '-m', 'pip', 'install', package],
            capture_output=True,
            text=True
        )
        if result.returncode != 0:
            failed.append(package)

    for package in to_reinstall_forced:
        # --force-reinstall replaces corrupted C extension DLLs
        result = subprocess.run(
            [python_exe, '-m', 'pip', 'install', '--force-reinstall', package],
            capture_output=True,
            text=True
        )
        if result.returncode != 0:
            failed.append(package)

    if failed:
        QMessageBox.warning(
            None,
            "NDMVRP — Installation Failed",
            f"These packages could not be installed automatically:\n\n"
            f"  {',  '.join(failed)}\n\n"
            f"Please install them manually by opening the OSGeo4W Shell "
            f"(as Administrator) and running:\n\n"
            f"  pip install --force-reinstall {' '.join(failed)}"
        )
    else:
        QMessageBox.information(
            None,
            "NDMVRP — Dependencies Ready",
            f"Successfully installed/repaired:  {',  '.join(all_to_fix)}\n\n"
            f"The plugin will now load."
        )


def _can_import(module_name):
    """Return True if module_name can be imported, False otherwise."""
    import importlib
    try:
        importlib.import_module(module_name)
        return True
    except Exception:
        return False


def _can_import_deep(test_expr):
    """Return True if test_expr executes without error, False otherwise.

    Used for packages whose top-level import succeeds even when the
    underlying C extension DLL is missing or corrupted (e.g. Pillow, lxml).
    """
    try:
        exec(test_expr)
        return True
    except Exception:
        return False