# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NDMVRP
                                 A QGIS plugin
 this plugin creates VRP strategies for NDM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-14
        copyright            : (C) 2023 by AEM
        email                : sid.mpadhyay@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

# =============================================================================
# STANDARD LIBRARY
# =============================================================================
import os
import os.path
import shutil
import subprocess
import sys

# =============================================================================
# THIRD-PARTY
# =============================================================================
import pandas as pd

# =============================================================================
# QGIS PyQt  — always use qgis.PyQt (never bare PyQt5) for version safety
# =============================================================================
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt, QVariant
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import (
    QAction, QDialog, QVBoxLayout, QFormLayout,
    QLineEdit, QPushButton, QLabel,
    QFileDialog, QTableWidget, QTableWidgetItem, QMessageBox
)

# =============================================================================
# QGIS CORE
# =============================================================================
from qgis.core import (
    QgsField,
    QgsFields,
    QgsVectorLayer,
    QgsProject,
    QgsCoordinateReferenceSystem,
)

# =============================================================================
# QGIS GUI
# =============================================================================
from qgis.gui import QgsMapToolEmitPoint
from qgis.utils import iface

# =============================================================================
# PLUGIN RESOURCES, DIALOGS AND ALGORITHMS
# =============================================================================
# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .NDMVRP_dialog import NDMVRPDialog
# Import algorithm functions
from .shortestpath_algo import shortestpath
from .datapoints_visualisation import visualize_points
from .datapoints_visualisation_10_final_with_routes_working_and_attributes_complete import (
    datapoints_visualisation_road_layer,
)
from .output_breakdown_for_visualisation_backend_3_final import output_breakdown

# =============================================================================
# CONSTANTS
# =============================================================================
ADD_DEPOT = 0
ADD_WAREHOUSE = 1
ADD_TRANSHIPMENT = 2
ADD_SIMULTANEOUS_NODES = 3
ADD_RELIEF_CENTER = 4
ADD_SPLIT_NODE = 5

# Mapping from button type to display text
button_type_text_mapping = {
    ADD_DEPOT: "Depot",
    ADD_WAREHOUSE: "Warehouse",
    ADD_TRANSHIPMENT: "Transhipment Port",
    ADD_SIMULTANEOUS_NODES: "Simultaneous Nodes",
    ADD_RELIEF_CENTER: "Relief Center",
    ADD_SPLIT_NODE: "Split Node"
}

PICKUP = "Pickup"
DELIVERY = "Delivery"


class MatrixInputDialog(QDialog):
    def __init__(self, vehicle_df, cargo_df):
        super(MatrixInputDialog, self).__init__()

        self.vehicle_df = vehicle_df
        self.cargo_df = cargo_df

        self.layout = QVBoxLayout(self)
        self.setWindowTitle("Vehicle to Load compatibility Information Input")

        # Get column names from cargo_df and set them as headers
        cargo_headers = [str(col) for col in cargo_df['Types']]
        self.rows = len(vehicle_df)
        self.cols = len(cargo_headers) + 2  # +1 for Vehicle Type, +1 for Remarks

        self.table = QTableWidget(self)
        self.table.setRowCount(self.rows)
        self.table.setColumnCount(self.cols)
        self.table.setHorizontalHeaderLabels(
            ['Vehicle Type'] + cargo_headers + ['Remarks/Comments'])

        # Set row values from vehicle_df['Vehicle Type'] (read-only)
        for row in range(self.rows):
            item = QTableWidgetItem(str(vehicle_df.iloc[row]['Vehicle Type']))
            item.setFlags(item.flags() ^ Qt.ItemIsEditable)
            self.table.setItem(row, 0, item)

        # Set default value as 1 for cargo columns
        for row in range(self.rows):
            for col in range(1, self.cols - 1):  # Exclude the last (Remarks) column
                item = QTableWidgetItem("1")
                self.table.setItem(row, col, item)

        self.ok_button = QPushButton('OK', self)
        self.cancel_button = QPushButton('Cancel', self)

        self.layout.addWidget(self.table)
        self.layout.addWidget(self.ok_button)
        self.layout.addWidget(self.cancel_button)

        self.ok_button.clicked.connect(self.accept)
        self.cancel_button.clicked.connect(self.reject)

    def get_matrix_data(self):
        matrix_data = []

        for row in range(self.rows):
            row_data = []
            for col in range(self.cols):
                item = self.table.item(row, col)
                if item:
                    if col == 0:
                        row_data.append(str(item.text()))
                    else:
                        row_data.append(float(item.text()))
                else:
                    # Default value is 1 if the cell is empty
                    row_data.append(1.0)
            matrix_data.append(row_data)

        matrix_df = pd.DataFrame(
            matrix_data,
            columns=['Vehicle Type'] + [str(col) for col in self.cargo_df['Types']] + ['Remarks/Comments']
        )
        return matrix_df


class FormDialogClass(QDialog):
    def __init__(self, fields):
        super(FormDialogClass, self).__init__()

        self.layout = QFormLayout(self)

        # Create line edit fields dynamically based on the fields list
        self.field_widgets = {}
        for field in fields:
            label = QLabel(f'{field}:', self)
            edit_field = QLineEdit(self)
            self.layout.addRow(label, edit_field)
            self.field_widgets[field] = edit_field

        self.ok_button = QPushButton('OK', self)
        self.cancel_button = QPushButton('Cancel', self)

        self.layout.addRow(self.ok_button, self.cancel_button)

        self.cancel_button.clicked.connect(self.cancel)

    def get_field_values(self):
        """Return the values entered in all fields as a dict."""
        for field, widget in self.field_widgets.items():
            print(field, widget.text())
        print("------------")
        return {field: widget.text() for field, widget in self.field_widgets.items()}

    def clear(self):
        """Clear all input fields."""
        for field, widget in self.field_widgets.items():
            widget.setText("")

    def cancel(self):
        """Clear fields and close the dialog."""
        self.clear()
        self.close()


# $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
# $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
# Main Plugin Code - NDMVRP
# $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
# $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

class NDMVRP:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'NDMVRP_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&NDMVRP')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        # ---------- Dialog Code ----------------#
        # Create an instance of FormDialogClass with the new fields list
        self.vehicle_fields = [
            "Vehicle Type", "Description", "Weight Capacity",
            "Volume Capacity", "Vehicle Network Compatibility",
            "Average Speed of Vehicle",
            "Must vehicles of this type finally return to their respective starting depots?", "Remarks/Comments"
        ]
        self.add_vehicle_dialog = FormDialogClass(self.vehicle_fields[1:])
        self.add_vehicle_dialog.ok_button.clicked.connect(
            self.addDataToVehicleTable)
        self.add_vehicle_dialog.setWindowTitle("Vehicle Information Input")

        self.cargo_fields = [
            "Pickup / Delivery", "Types", "Description", "Unit Weight", "Unit Volume", "Remarks/Comments"
        ]
        self.add_pickup_dialog = FormDialogClass(self.cargo_fields[2:])
        self.add_pickup_dialog.ok_button.clicked.connect(
            self.addDataToPickupTable)
        self.add_pickup_dialog.setWindowTitle("Cargo pickup Information Input")

        self.add_delivery_dialog = FormDialogClass(self.cargo_fields[2:])
        self.add_delivery_dialog.ok_button.clicked.connect(
            self.addDataToDeliveryTable)
        self.add_delivery_dialog.setWindowTitle(
            "Cargo delivery Information Input")

        # ---------- Depot Details table ----------------#
        self.depot_table_fields = [
            "Sl. No.", "Description", "Latitude", "Longitude",
            "Multimodal Compatibility for Network_1",
            "Multimodal Compatibility for Network_2",
            "Multimodal Compatibility for Network_3", "Remarks/Comments"
        ]

        self.depot_table_fields_new = []
        self.vehicle_ids = []
        self.pickup_ids = []
        self.delivery_ids = []

        # ----------- Custom tables  ------------#
        self.vehicle_df = pd.DataFrame(columns=self.vehicle_fields)
        self.cargo_df = pd.DataFrame(columns=self.cargo_fields)
        self.matrix_df = None

        # ----------- Get lat long  ------------#
        self.get_lat_long_tool = None
        self.location_df = None
        self.location_df_fields = []
        self.latitude = None
        self.longitude = None
        self.button_id_mapping = {}
        self.button_type = None

        # ----------- Depot Layer  ------------#
        self.depot_layer = None
        self.df = None

    # noinspection PyMethodMayBeStatic

    ######### add custom functions for buttons #########

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started

        if self.first_start == True:
            self.first_start = False
            self.dlg = NDMVRPDialog()
            self.dlg.setFixedSize(self.dlg.size())

            # &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
            # -- Buttons click events --#
            #### Upper Buttons ####
            self.dlg.add_vehicle_type_pb.clicked.connect(self.add_vehicle_type)
            self.dlg.add_pickup_cargo_pb.clicked.connect(self.add_pickup_cargo)
            self.dlg.add_delivery_cargo_pb.clicked.connect(
                self.add_delivery_cargo)
            self.dlg.save_vehicle_cargo_data.clicked.connect(
                self.generate_matrix_data)

            #### Lower Buttons ####
            self.canvas = self.iface.mapCanvas()
            if self.get_lat_long_tool is None:
                self.get_lat_long_tool = QgsMapToolEmitPoint(
                    self.canvas)

            self.dlg.add_depot_pb.clicked.connect(lambda: self.button_clicked_type(ADD_DEPOT))
            self.dlg.add_warehouse_pb.clicked.connect(lambda: self.button_clicked_type(ADD_WAREHOUSE))
            self.dlg.add_transhipment_pb.clicked.connect(lambda: self.button_clicked_type(ADD_TRANSHIPMENT))
            self.dlg.add_simultaneous_nodes_pb.clicked.connect(lambda: self.button_clicked_type(ADD_SIMULTANEOUS_NODES))
            self.dlg.add_relief_center_pb.clicked.connect(lambda: self.button_clicked_type(ADD_RELIEF_CENTER))
            self.dlg.add_split_node_pb.clicked.connect(lambda: self.button_clicked_type(ADD_SPLIT_NODE))

            self.dlg.save_depot_data_pb.clicked.connect(self.save_all_data)
            self.dlg.clear_location_table_pb.clicked.connect(
                self.clear_location_table)
            self.dlg.save_depot_data_pb_3.clicked.connect(self.reset_vrp)

            self.dlg.distance_table_pb.clicked.connect(
                self.generate_travel_cost_tables)

            self.dlg.run_vrp_pb.clicked.connect(self.run_vrp)

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            pass

    def tr(self, message):
        """Get the translation for a string using Qt translation API."""
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('NDMVRP', message)

    def add_action(
            self,
            icon_path,
            text,
            callback,
            enabled_flag=True,
            add_to_menu=True,
            add_to_toolbar=True,
            status_tip=None,
            whats_this=None,
            parent=None):
        """Add a toolbar icon to the toolbar."""

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = os.path.join(self.plugin_dir, 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u'NDMVRP'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&NDMVRP'),
                action)
            self.iface.removeToolBarIcon(action)

    def fill_table(self):
        self.dlg.table.clear()
        depot_id_li = []
        depot_lat_li = []
        depot_lon_li = []
        depot_pickup_li = []
        depot_delivery_li = []
        for feature in self.depot_layer.getFeatures():
            depot_id_li.append(feature['depot_id'])
            depot_lat_li.append(feature['depot_lat'])
            depot_lon_li.append(feature['depot_lon'])
            depot_pickup_li.append(feature['pickup'])
            depot_delivery_li.append(feature['delivery'])

        self.dlg.table.setRowCount(len(depot_id_li))
        for row in range(len(depot_id_li)):
            depot_id = QTableWidgetItem(str(depot_id_li[row]))
            depot_lat = QTableWidgetItem(str(round(depot_lat_li[row], 6)))
            depot_lon = QTableWidgetItem(str(round(depot_lon_li[row], 6)))
            depot_pickup = QTableWidgetItem(str(depot_pickup_li[row]))
            depot_delivery = QTableWidgetItem(str(depot_delivery_li[row]))

            self.dlg.table.setItem(row, 0, depot_id)
            self.dlg.table.setItem(row, 1, depot_lat)
            self.dlg.table.setItem(row, 2, depot_lon)
            self.dlg.table.setItem(row, 3, depot_pickup)
            self.dlg.table.setItem(row, 4, depot_delivery)

        self.df = pd.DataFrame(
            list(zip(depot_id_li, depot_lat_li, depot_lon_li, depot_pickup_li, depot_delivery_li)),
            columns=['Depot_ID', 'Depot_latitude', 'Depot_longitude', 'Depot_pickup', 'Depot_delivery']
        )

    def on_add_new_depot_feature(self, featureId):
        layer = self.depot_layer
        feature = layer.getFeature(featureId)
        depot_latitude = feature.geometry().asPoint().y()
        depot_longitude = feature.geometry().asPoint().x()
        if layer.featureCount() == 1:
            depot_id = 1
        else:
            depot_id = int(layer.maximumValue(
                layer.fields().indexFromName('depot_id'))) + 1

        self.stopFile_field_dict = {}
        fields = layer.dataProvider().fields()
        for i in range(fields.count()):
            field = fields.field(i)
            self.stopFile_field_dict[field.name()] = i
        feature.setAttribute(self.stopFile_field_dict['depot_id'], depot_id)
        feature.setAttribute(self.stopFile_field_dict['depot_lat'], depot_latitude)
        feature.setAttribute(self.stopFile_field_dict['depot_lon'], depot_longitude)
        feature.setAttribute(self.stopFile_field_dict['pickup'], feature['pickup'])
        feature.setAttribute(self.stopFile_field_dict['delivery'], feature['delivery'])
        layer.updateFeature(feature)
        layer.updateExtents()

    def save_depot_data(self):
        location_file_name = 'location_data.csv'
        location_file_path, _ = QFileDialog.getSaveFileName(
            None, "Save Location DataFrame CSV", location_file_name, "CSV Files (*.csv)")
        if location_file_path:
            self.location_df.to_csv(location_file_path, index=False)
            print(f'Location DataFrame saved to {location_file_path}')
            QMessageBox.information(
                None, "Success", "Files has been extracted to output path.")

    def select_depot(self):
        if self.depot_layer is None:
            fields = QgsFields()
            fields.append(QgsField("depot_id", QVariant.String))
            fields.append(QgsField("depot_lat", QVariant.Double))
            fields.append(QgsField("depot_lon", QVariant.Double))
            fields.append(QgsField("pickup", QVariant.Int))
            fields.append(QgsField("delivery", QVariant.Int))

            crs = QgsCoordinateReferenceSystem('EPSG:4326')

            layer_name = "Depot_Layer"
            layer = QgsVectorLayer(
                f"Point?crs={crs.authid()}&field=depot_id:string&field=depot_lat:double&field=depot_lon:double&field=pickup:integer&field=delivery:integer",
                layer_name,
                "memory"
            )

            layer_provider = layer.dataProvider()
            layer_provider.addAttributes(fields)
            layer.updateFields()

            QgsProject.instance().addMapLayer(layer)
            self.depot_layer = layer

        if not self.depot_layer.isEditable():
            self.depot_layer.startEditing()
            iface.setActiveLayer(self.depot_layer)
            self.depot_layer.featureAdded.connect(
                self.on_add_new_depot_feature)

    # NOTE: extract_csv() was a legacy development function with a hardcoded
    # path to a specific developer machine ("C:\\Users\\Rahul\\..."). It is
    # not connected to any UI button and is retained here only for reference.
    # Do not use it as-is; it will crash on any other machine.
    # def extract_csv(self):
    #     ...

    # ------------------------------------
    # $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
    ###### Custom Function For Buttons ######
    # $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
    # ------------------------------------

    def assignIdsToButtonType(self):
        self.button_id_mapping = {}
        self.button_id_mapping[ADD_DEPOT] = self.vehicle_ids
        self.button_id_mapping[ADD_WAREHOUSE] = self.delivery_ids
        self.button_id_mapping[ADD_TRANSHIPMENT] = self.pickup_ids + \
            self.delivery_ids
        self.button_id_mapping[ADD_SIMULTANEOUS_NODES] = self.pickup_ids + \
            self.delivery_ids
        self.button_id_mapping[ADD_RELIEF_CENTER] = self.pickup_ids
        self.button_id_mapping[ADD_SPLIT_NODE] = self.pickup_ids + \
            self.delivery_ids

    # ###### add Vehicle Button ######

    def add_vehicle_type(self):
        self.add_vehicle_dialog.show()

    def addDataToVehicleTable(self):
        print("OK clicked")
        field_values = self.add_vehicle_dialog.get_field_values()

        print("addDataToVehicleTable() - field_values", field_values)
        size = len(self.vehicle_df)
        field_values = {self.vehicle_fields[0]: f"VT{size+1}", **field_values}
        self.vehicle_df = pd.concat(
            [self.vehicle_df, pd.DataFrame([field_values])], ignore_index=True)

        self.dlg.vehicle_details.clear()
        self.dlg.vehicle_details.setHorizontalHeaderLabels(self.vehicle_fields)

        print("addDataToVehicleTable() - vehicle_df len", len(self.vehicle_df))
        self.dlg.vehicle_details.setRowCount(len(self.vehicle_df))
        for row in range(len(self.vehicle_df)):
            for col in range(len(self.vehicle_df.columns)):
                self.dlg.vehicle_details.setItem(
                    row, col, QTableWidgetItem(str(self.vehicle_df.iloc[row, col])))

        self.add_vehicle_dialog.clear()
        self.add_vehicle_dialog.accept()
        print("-----------------")

    # ------- add Vehicle Button  END --------#

    # ###### add Pickup Cargo Button ######
    def add_pickup_cargo(self):
        self.add_pickup_dialog.show()

    def addDataToPickupTable(self):
        field_values = self.add_pickup_dialog.get_field_values()
        if self.cargo_df is None:
            self.cargo_df = pd.DataFrame(columns=self.cargo_fields)

        print("addDataToPickupTable() - field_values", field_values)
        p_size = len(self.cargo_df[self.cargo_df['Pickup / Delivery'] == PICKUP])
        field_values = {self.cargo_fields[0]: PICKUP,
                        self.cargo_fields[1]: f"CC{p_size+1}P", **field_values}
        self.cargo_df = pd.concat([self.cargo_df, pd.DataFrame(
            [field_values])], ignore_index=True)

        self.dlg.cargo_details.clear()
        self.dlg.cargo_details.setHorizontalHeaderLabels(self.cargo_fields)

        print("addDataToPickupTable() - cargo_df len", len(self.cargo_df))
        self.dlg.cargo_details.setRowCount(len(self.cargo_df))
        for row in range(len(self.cargo_df)):
            for col in range(len(self.cargo_df.columns)):
                self.dlg.cargo_details.setItem(
                    row, col, QTableWidgetItem(str(self.cargo_df.iloc[row, col])))

        self.add_pickup_dialog.clear()
        self.add_pickup_dialog.accept()
        print("-----------------")

    # ------- add Pickup Cargo Button  END --------#

    # ###### add Delivery Cargo Button ######
    def add_delivery_cargo(self):
        self.add_delivery_dialog.show()

    def addDataToDeliveryTable(self):
        field_values = self.add_delivery_dialog.get_field_values()
        if self.cargo_df is None:
            self.cargo_df = pd.DataFrame(columns=self.cargo_fields)

        print("addDataToDeliveryTable() - field_values", field_values)
        d_size = len(self.cargo_df[self.cargo_df['Pickup / Delivery'] == DELIVERY])
        field_values = {self.cargo_fields[0]: DELIVERY,
                        self.cargo_fields[1]: f"CC{d_size+1}D", **field_values}
        self.cargo_df = pd.concat([self.cargo_df, pd.DataFrame(
            [field_values])], ignore_index=True)

        self.dlg.cargo_details.clear()
        self.dlg.cargo_details.setHorizontalHeaderLabels(self.cargo_fields)

        print("addDataToDeliveryTable() - cargo_df len", len(self.cargo_df))
        self.dlg.cargo_details.setRowCount(len(self.cargo_df))
        for row in range(len(self.cargo_df)):
            for col in range(len(self.cargo_df.columns)):
                self.dlg.cargo_details.setItem(
                    row, col, QTableWidgetItem(str(self.cargo_df.iloc[row, col])))

        self.add_delivery_dialog.clear()
        self.add_delivery_dialog.accept()
        print("-----------------")

    # ------- add Delivery Cargo Button  END --------#

    # ------- save_vehicle_cargo_data Button  START --------#
    def generate_matrix_data(self):
        print("generate_matrix_data()")
        matrix_dialog = MatrixInputDialog(self.vehicle_df, self.cargo_df)
        result = matrix_dialog.exec_()
        if result == QDialog.Accepted:
            self.matrix_df = matrix_dialog.get_matrix_data()
            print("Matrix Data:")
            print(self.matrix_df)

        # Rebuild the location details table columns
        self.depot_table_fields_new = [field for field in self.depot_table_fields]
        self.vehicle_ids = [id for id in self.vehicle_df['Vehicle Type']]
        self.depot_table_fields_new.extend(["Vertex Category"])
        self.depot_table_fields_new.extend(self.vehicle_ids)

        self.pickup_ids = [
            id for id in self.cargo_df[self.cargo_df['Pickup / Delivery'] == 'Pickup']['Types']]
        self.depot_table_fields_new.extend(self.pickup_ids)
        print("pickup_ids", self.pickup_ids)

        self.delivery_ids = [
            id for id in self.cargo_df[self.cargo_df['Pickup / Delivery'] == 'Delivery']['Types']]
        self.depot_table_fields_new.extend(self.delivery_ids)
        print("delivery_ids", self.delivery_ids)

        self.assignIdsToButtonType()

        print("self.depot_table_fields_new", self.depot_table_fields_new)
        self.dlg.depot_details.clear()
        self.dlg.depot_details.setColumnCount(len(self.depot_table_fields_new))
        self.dlg.depot_details.setHorizontalHeaderLabels(
            self.depot_table_fields_new)

    # ------- save_vehicle_cargo_data Button  END --------#

    # ###### add Depot Button ######

    def button_clicked_type(self, button_type):
        # --- Prerequisite validation ---
        if len(self.vehicle_df) == 0:
            QMessageBox.warning(
                None,
                "Step Incomplete",
                "Please add at least one vehicle using the 'Add Vehicle Type' button before adding locations."
            )
            return

        if len(self.cargo_df) == 0:
            QMessageBox.warning(
                None,
                "Step Incomplete",
                "Please add at least one cargo item using the 'Add Pickup/Delivery Cargo' buttons before adding locations."
            )
            return

        if self.matrix_df is None:
            QMessageBox.warning(
                None,
                "Step Incomplete",
                "Please fill in the Vehicle-Cargo Compatibility table using the 'Save Vehicle & Cargo Data' button before adding locations."
            )
            return
        # --- End validation ---

        self.button_type = button_type
        self.dlg.showMinimized()
        self.get_lat_long_tool.canvasClicked.connect(self.clickHandler)
        self.canvas.setMapTool(self.get_lat_long_tool)

    def clickHandler(self, point):
        print("Clicked: ", point.x(), point.y())
        if self.location_df is None:
            self.location_df = pd.DataFrame(
                columns=self.depot_table_fields_new)

        self.latitude = point.y()
        self.longitude = point.x()
        print("Latitude: ", self.latitude)
        print("Longitude: ", self.longitude)

        depot_dailog_fields = [
            "Description", "Multimodal Compatibility for Network_1", "Multimodal Compatibility for Network_2",
            "Multimodal Compatibility for Network_3", "Remarks/Comments"] + self.button_id_mapping[self.button_type]
        self.depot_dailog = FormDialogClass(depot_dailog_fields)
        self.depot_dailog.ok_button.clicked.connect(
            lambda: self.addDataToDepotTable(self.button_type))

        self.depot_dailog.setWindowTitle(
            f"{button_type_text_mapping[self.button_type]} Information Input")
        self.depot_dailog.show()
        result = self.depot_dailog.exec_()
        if result == QDialog.Accepted:
            print("Dialog accepted")

        self.dlg.showNormal()
        self.canvas.unsetMapTool(self.get_lat_long_tool)
        self.get_lat_long_tool.canvasClicked.disconnect(self.clickHandler)

    def addNoDescriptionLatLong(self, size, description, button_type, field_values):
        id_text = None
        vertex_category = None

        if button_type == ADD_DEPOT:
            id_text = "VD"
            vertex_category = "Vehicle Depot"
            size = len(self.location_df[self.location_df['Sl. No.'].str.startswith(id_text)])
        elif button_type == ADD_WAREHOUSE:
            id_text = "WH"
            vertex_category = "WareHouse"
            size = len(self.location_df[self.location_df['Sl. No.'].str.startswith(id_text)])
        elif button_type == ADD_TRANSHIPMENT:
            id_text = "TP"
            vertex_category = "Transhipment Port"
            size = len(self.location_df[self.location_df['Sl. No.'].str.startswith(id_text)])
        elif button_type == ADD_SIMULTANEOUS_NODES:
            id_text = "NM"
            vertex_category = "Simultaneous Node"
            size = len(self.location_df[self.location_df['Sl. No.'].str.startswith(id_text)])
        elif button_type == ADD_RELIEF_CENTER:
            id_text = "RC"
            vertex_category = "Relief Centre"
            size = len(self.location_df[self.location_df['Sl. No.'].str.startswith(id_text)])
        elif button_type == ADD_SPLIT_NODE:
            id_text = "NP"
            vertex_category = "Split Node"
            size = len(self.location_df[self.location_df['Sl. No.'].str.startswith(id_text)])

        row_data = {self.depot_table_fields_new[0]: f"{id_text}{size+1}"}
        row_data["Vertex Category"] = vertex_category
        row_data[self.depot_table_fields_new[1]] = description
        row_data[self.depot_table_fields_new[2]] = self.latitude
        row_data[self.depot_table_fields_new[3]] = self.longitude
        for field in ["Multimodal Compatibility for Network_1", "Multimodal Compatibility for Network_2",
                      "Multimodal Compatibility for Network_3", "Remarks/Comments"]:
            row_data[field] = field_values.get(field, "")

        return row_data

    def addDataToDepotTable(self, button_type):
        field_values = self.depot_dailog.get_field_values()
        print("addDataToDepotTable() - field_values", field_values)
        size = len(self.location_df)
        row_data = self.addNoDescriptionLatLong(
            size, field_values['Description'], self.button_type, field_values)
        combined_list = self.vehicle_ids + self.pickup_ids + self.delivery_ids
        for ids in combined_list:
            row_data[ids] = 0

        for field in self.button_id_mapping[button_type]:
            row_data[field] = field_values[field]

        self.location_df = pd.concat(
            [self.location_df, pd.DataFrame([row_data])], ignore_index=True)

        self.dlg.depot_details.clear()
        self.dlg.depot_details.setHorizontalHeaderLabels(
            self.depot_table_fields_new + ["Vertex Category"])
        print("addDataToDepotTable() - location_df len", len(self.location_df))
        self.dlg.depot_details.setRowCount(len(self.location_df))
        for row in range(len(self.location_df)):
            for col in range(len(self.location_df.columns)):
                self.dlg.depot_details.setItem(
                    row, col, QTableWidgetItem(str(self.location_df.iloc[row, col])))

        self.depot_dailog.clear()
        self.depot_dailog.accept()
        self.depot_dailog = None

    # ------- add Depot Button  END --------#

    # ------- clear_location_table_data Button  START --------#
    def clear_location_table(self):
        self.location_df = None
        self.dlg.depot_details.clear()
        self.dlg.depot_details.setHorizontalHeaderLabels(
            self.depot_table_fields_new)
        self.dlg.depot_details.setRowCount(0)

    # ------- clear_location_table_data Button  END --------#

    # ------- reset_vrp Button  START --------#

    def reset_vrp(self):
        """Reset the entire plugin UI and all data back to initial state."""
        confirm = QMessageBox.question(
            None,
            "Reset VRP",
            "This will clear all vehicles, cargo, compatibility data, and locations. Are you sure?",
            QMessageBox.Yes | QMessageBox.No
        )
        if confirm == QMessageBox.No:
            return

        # --- Reset all dataframes ---
        self.vehicle_df = pd.DataFrame(columns=self.vehicle_fields)
        self.cargo_df = pd.DataFrame(columns=self.cargo_fields)
        self.matrix_df = None
        self.location_df = None
        self.vehicle_ids = []
        self.pickup_ids = []
        self.delivery_ids = []
        self.depot_table_fields_new = []
        self.button_id_mapping = {}
        self.button_type = None

        # --- Reset all UI tables ---
        self.dlg.vehicle_details.clearContents()
        self.dlg.vehicle_details.setRowCount(0)

        self.dlg.cargo_details.clearContents()
        self.dlg.cargo_details.setRowCount(0)

        self.dlg.depot_details.clearContents()
        self.dlg.depot_details.setRowCount(0)
        self.dlg.depot_details.setColumnCount(0)

        QMessageBox.information(None, "Reset Complete", "Plugin has been reset. You can start again.")

    # ------- reset_vrp Button  END --------#

    # ------- save_all_data Button  START --------#

    def save_all_data(self):
        output_folder_path = QFileDialog.getExistingDirectory(
            None, "Select Output Folder")
        if not output_folder_path:
            print("No output folder selected. Exiting.")
            return

        files_and_dfs = [
            ('0 Vehicles.csv', self.vehicle_df),
            ('0 Cargo.csv', self.cargo_df),
            ('1 Vehicle Cargo Compatibility and Loading Unloading Time.csv', self.matrix_df),
            ('1 Locations and PickUp Delivery details.csv', self.location_df)
        ]

        for file_name, df in files_and_dfs:
            file_path = os.path.join(output_folder_path, file_name)
            df.to_csv(file_path, index=False)
            print(f'DataFrame saved to {file_path}')

        QMessageBox.information(
            None, "Success", "Files have been extracted to output path.")

    def generate_travel_cost_tables(self):
        points_df = self.location_df.copy()
        points_df['No'] = points_df['Sl. No.']
        points_df = points_df[['No', 'Latitude', 'Longitude']]
        print("points_df")

        road_layers = [
            "Networks/Network_1.gpkg",
            "Networks/Network_2.gpkg",
            "Networks/Network_3.gpkg"
        ]
        output_csv_names = [
            "Distance_Matrix_for_Network_1.csv",
            "Distance_Matrix_for_Network_2.csv",
            "Distance_Matrix_for_Network_3.csv"
        ]
        output_layer_names = [
            "Distance Matrix for Network 1",
            "Distance Matrix for Network 2",
            "Distance Matrix for Network 3"
        ]

        output_folder_path = QFileDialog.getExistingDirectory(
            None, "Select Output Folder")
        if not output_folder_path:
            print("No output folder selected. Exiting.")
            return

        points_df1 = self.location_df.copy()
        visualize_points(points_df1)

        for road_layer, output_csv_name, output_name in zip(road_layers, output_csv_names, output_layer_names):
            output_csv_path = os.path.join(output_folder_path, output_csv_name)
            shortestpath(points_df, road_layer, output_csv_path, output_name)
            print(f'Travel Cost DataFrame saved to {output_csv_path}')

        QMessageBox.information(
            None, "Success", "Files have been extracted to output path.")

    def run_vrp(self):
        print("run_vrp() - function has started running")

        current_dir = os.path.dirname(os.path.abspath(__file__))
        print(f"Current script directory: {current_dir}")
        psr_gip_heuristic_file_location = os.path.join(current_dir, "PSR_GIP.py")

        # Get the Input CSV folder path from the user
        userDefined_INPUT_location_of_CSV = QFileDialog.getExistingDirectory(
            None, "Select the Folder Containing the input CSV Files")

        if not userDefined_INPUT_location_of_CSV:
            print("No Folder selected. Exiting.")
            return

        userDefined_INPUT_location_of_CSV += "/"

        # Write path files to plugin directory so PSR_GIP.py can read them
        input_path_file = os.path.join(current_dir, "userDefined_INPUT_location_of_CSV.txt")
        with open(input_path_file, 'w') as f:
            f.write(userDefined_INPUT_location_of_CSV)
            print(f"Input path written to: {input_path_file}")

        OUTPUT_location = userDefined_INPUT_location_of_CSV + "OutPut/"

        output_path_file = os.path.join(current_dir, "userDefined_OUTPUT_location.txt")
        with open(output_path_file, 'w') as f:
            f.write(OUTPUT_location)
            print(f"Output path written to: {output_path_file}")

        # Remove any previously existing output directory
        if os.path.exists(OUTPUT_location) and os.path.isdir(OUTPUT_location):
            try:
                shutil.rmtree(OUTPUT_location)
                print(f"Deleted existing output directory: '{OUTPUT_location}'")
            except Exception as e:
                print(f"Error deleting output directory: {e}")
        else:
            print(f"No existing output directory at: '{OUTPUT_location}'")

        print("Creating output directory...")
        os.makedirs(OUTPUT_location)

        # Find the correct Python interpreter
        # In QGIS, sys.executable points to qgis-bin.exe, NOT python.exe
        python_exe = os.path.join(sys.exec_prefix, 'python.exe')
        if not os.path.exists(python_exe):
            python_exe = sys.executable  # fallback for non-Windows
        print(f"Using Python interpreter: {python_exe}")

        # Run the heuristic and capture its output for debugging
        result = subprocess.run(
            [python_exe, psr_gip_heuristic_file_location],
            capture_output=True,
            text=True,
            cwd=current_dir  # ensure PSR_GIP.py runs with plugin dir as working directory
        )
        print("--- Heuristic stdout ---")
        print(result.stdout)
        print("--- Heuristic stderr ---")
        print(result.stderr)
        print(f"Return code: {result.returncode}")

        # Check for output file first — the heuristic may have succeeded even if
        # the visualization step crashed (returncode != 0)
        best_OUTPUT_file_location = OUTPUT_location + "MakeSPAN_OutPut_0.xlsx"

        if not os.path.exists(best_OUTPUT_file_location):
            # File missing — the heuristic genuinely failed
            QMessageBox.critical(
                None,
                "Heuristic Failed",
                f"The VRP heuristic did not produce the expected output file.\n\n"
                f"{result.stderr[-600:] if result.stderr else 'No error details.'}\n\n"
                f"Check the Python console for the full log."
            )
            return

        if result.returncode != 0:
            # File exists but non-zero exit (e.g. visualization crash) — warn but continue
            print("Warning: Heuristic exited with errors but output file was produced. Proceeding...")

        print("Subprocess completed — output file found, continuing...")

        # Read the best output file
        merged_df = pd.read_excel(best_OUTPUT_file_location)

        # Run output breakdown for visualisation
        output_df = output_breakdown(merged_df, userDefined_INPUT_location_of_CSV)

        # Save the processed output CSV
        output_filename = "OutPut ordered with latitude and longitude.csv"
        output_file_path = os.path.join(userDefined_INPUT_location_of_CSV, output_filename)
        output_df.to_csv(output_file_path, index=False)

        # Run route visualisation
        datapoints_visualisation_road_layer(output_df)

        print("run_vrp() - function has finished running successfully")